services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: next-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000 # URL del backend para desarrollo local
